name: alpha

on:
  workflow_dispatch:
        
jobs:
  test-matlab:
    name: Run MATLAB Scripts
    runs-on: ubuntu-20.04
    steps:
    
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        
      # Use @master, otherwise the system setup fails
      - name: Check out repository
        uses: actions/checkout@v2        
        
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: ver

