name: alpha

on:
  workflow_dispatch:
        
jobs:
  test-matlab:
    name: Run MATLAB Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALL_ACCESS2 }}
        
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: ver

