# This is a basic workflow to help you get started with Actions

name: alpha

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  create:
    tags:
      - release*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone master
      uses: actions/checkout@v2
      with:
        path: test
        fetch-depth: 0
        
    - name: List tags
      run: |
        cd $GITHUB_WORKSPACE/test
        git log --tags

