name: alpha

on:
  workflow_dispatch:
        
jobs:
  test-matlab:
    name: Run MATLAB Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
        
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@master
        
      - name: Run script
        uses: matlab-actions/run-command@master
        with:
          command: testScript
        
      - name: Run script
        uses: matlab-actions/run-command@master
        with:
          command: testError
