name: alpha

on:
  create:
    tags:
      - release*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone master
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}      
        fetch-depth: 0
        
    - name: List tags
      run: |
        git log

