name: alpha

on:
  push:
    tags:
      - 'release*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone master
      uses: actions/checkout@master
      #with:
        #ref: ${{ github.ref }}      
        #fetch-depth: 0
        
    - name: List tags
      run: |
        echo "${{ github.ref }}"
