name: alpha

on:
  push:
    tags:
      - 'release*'

  workflow_dispatch:
        
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Verify existence of release notes
        id: release_notes
        run: |
          if ! test -e .release-notes; then
            exit 1
          fi  
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.release_notes.conclusion=='success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release-${{ github.ref }}
          body_path: .release-notes
          draft: false
          prerelease: false

          

